# Generated by Django 5.1.15 on 2026-07-21 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateField(db_index=True)),
                ('end_at', models.DateField(db_index=True)),
                ('all_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('color', models.CharField(default='#0EA5E9', max_length=7)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('task', 'Task'), ('manual', 'Manual'), ('meeting', 'Meeting')], default='manual', max_length=16)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='projects.project')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event', to='tasks.task')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['start_at', 'start_time'],
                'indexes': [models.Index(fields=['workspace', 'start_at', 'end_at'], name='calendar_ev_workspa_7b78ef_idx'), models.Index(fields=['workspace', 'assignee'], name='calendar_ev_workspa_b37051_idx'), models.Index(fields=['workspace', 'project'], name='calendar_ev_workspa_2483dc_idx'), models.Index(fields=['workspace', 'source'], name='calendar_ev_workspa_156307_idx')],
            },
        ),
    ]
